## Homework 1 - Generating random numbers
### Rafael J. Mantilla - 201124446

We wish to generate a set of random numbers such that the sum of all of them is 1. To do this the first approach is to generate n random numbers and divide by the sum of them:

In [ ]:
import math
import numpy as np
import random

def genRandomNumbers(n):
    numbers = np.random.random(n)
    r = numbers/np.sum(numbers)
    return r


We test this method:

In [56]:
result = genRandomNumbers(50)
result.shape= (10, 5)
print(result)
print("Sum of numbers: ",np.sum(result))

[[ 0.0167649   0.04243868  0.04115585  0.00949049  0.01349623]
 [ 0.02827183  0.01041426  0.01318958  0.01662888  0.00153306]
 [ 0.00817357  0.03616943  0.02276541  0.00650139  0.00275568]
 [ 0.01320584  0.01275379  0.01972553  0.03048267  0.02325274]
 [ 0.03912722  0.0004999   0.0285396   0.04540847  0.02001361]
 [ 0.01517094  0.02546184  0.00484445  0.02442472  0.00919804]
 [ 0.0315442   0.04370647  0.0099419   0.03739028  0.02371665]
 [ 0.02836388  0.00781755  0.02703931  0.02748751  0.01488405]
 [ 0.02106436  0.00806113  0.04450566  0.0025009   0.00395877]
 [ 0.0096769   0.04560597  0.00532868  0.02050558  0.00504162]]
Sum of numbers:  1.0


Note however that this method does not generate a uniform random over the simplex
$$\sum\limits_{i=1}^n x_i = 1, \qquad x_i \in [0,1) \,\,\forall i$$
We exhibit this fact generating two random numbers and checking if the first one is greater than 0.9. If the numbers were uniformly generated we would expect this to ocurr 10% of the times:

In [42]:
def testDistro (generator):
    cont = 0
    for i in range(1,100000):
        r = generator(2)
        if(r[0]>0.9):
            cont+=1
    print("The first number was greater than 0.9,",cont/1000,"% of the tests.")

testDistro(genRandomNumbers)
%timeit genRandomNumbers(10000)

The first number was greater than 0.9, 5.475 % of the tests.
10000 loops, best of 3: 101 µs per loop


Generating a uniform distribution over a polytope is an interesting problem outside the scope of this course. We exhibit two other methods in which we can generate random numbers. First we use the Dirchlet distribution (https://en.wikipedia.org/wiki/Dirichlet_distribution). This distribution of course is far from the uniform distribution, however it allows you to assign specific weights to each value and has many important uses. This solves our problem in a unique way but may be too slow for generating big samples:

In [51]:
def genDirichlet(n):
    #We assign equal weights to every element
    return numpy.random.dirichlet([1 for i in range(1,n+1)])

We test this method, note that :

In [59]:
result = genDirichlet(50)
result.shape= (10, 5)
print(result)
print("Sum of numbers: ",np.sum(result))
testDistro(genDirichlet)
%timeit genDirichlet(10000)

[[ 0.00242094  0.04283598  0.02293029  0.00886232  0.03360806]
 [ 0.11515103  0.02045271  0.00529303  0.01305147  0.00894993]
 [ 0.0012646   0.00734888  0.01159935  0.01515866  0.01806239]
 [ 0.00223048  0.02697281  0.02264462  0.04379689  0.00044209]
 [ 0.00805795  0.01449295  0.02003482  0.01657966  0.00717353]
 [ 0.00174778  0.03821572  0.02975769  0.02253871  0.00539277]
 [ 0.026548    0.01073457  0.06623237  0.00042132  0.07244201]
 [ 0.00410546  0.00650369  0.02049357  0.00133453  0.02365063]
 [ 0.01754688  0.0009024   0.02014108  0.02174597  0.04248681]
 [ 0.01973533  0.00308361  0.0385497   0.01348668  0.0027873 ]]
Sum of numbers:  1.0
The first number was greater than 0.9, 10.137 % of the tests.
1000 loops, best of 3: 1.27 ms per loop
