<!-- <img src="files/images/python-screenshot.jpg" width="600"> -->
<img src="imgs/header.png">

## Basics of Numerical Python Arrays (numpy)

### 1. In-place Arithmetics

In [1]:
import numpy as np

#### Case 1: a = a+b 
The sum is first computed and resulting in a new array and the a is bound to the new array

In [2]:
a = np.array(range(10000000))
b = np.array(range(9999999,-1,-1))

In [3]:
%%time
a = a + b 

Wall time: 40.6 ms


#### Case 2: a += b 
The elements of b are directly added into the elements of a (in memory) - no intermediate array. These operators implement the so-called "in-place arithmetics" (e.g., +=, *=, /=, -= )  

In [4]:
a = np.array(range(10000000))
b = np.array(range(9999999,-1,-1))

In [5]:
%%time
a +=b 

Wall time: 27.6 ms


### 2. Vectorization

In [7]:
#Apply function to a complete array instead of writing loop to iterate over all elements of the array. 
#This is called vectorization. The opposite of vectorization (for loops) is known as the scalar implementation

def f(x):
    return x*np.exp(4)

print(f(b))

[  5.45981446e+08   5.45981391e+08   5.45981337e+08 ...,   1.09196300e+02
   5.45981500e+01   0.00000000e+00]


### 3. Slicing and reshape

#### Array slicing
    x[i:j:s] 
picks out the elements starting with index i and stepping s indices at the time up to, but not including, j.

In [10]:
x = np.array(range(100))

x[1:-1] # picks out all elements except the first and the last, but contrary to lists, a[1:-1] is not a copy of the data in a.
#x[0:-1:2] # picks out every two elements up to, but not including, the last element, while 
#x[::4] # picks out every four elements in the whole array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

#### Array shape manipulation



In [14]:
a = np.linspace(-1, 1, 6)
print (a)

a.shape
a.size

#rows, columns
a.shape = (2, 3) 
a = a.reshape(2, 3) # alternative

a.shape
print (a)

# len(a) always returns the length of the first dimension of an array. -> no. of rows

[-1.  -0.6 -0.2  0.2  0.6  1. ]


6

## Exercise
### 1. Create a 10x10 2d array with 1 on the border and 0 inside

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### 2. Create a structured array representing a position (x,y) and a color (r,g,b)

In [16]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))
 ((0.0, 0.0), (0.0, 0.0, 0.0)) ((0.0, 0.0), (0.0, 0.0, 0.0))]


### 3. Consider a large vector Z, compute Z to the power of 3 using 2 different methods

In [17]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':


1 loop, best of 3: 1.67 s per loop
1 loop, best of 3: 288 ms per loop
